default['nservicebus']['serviceinsight']['sha256checksum'] = ''
default['nservicebus']['serviceinsight']['url'] = ''
default['nservicebus']['servicepulse']['sha256checksum'] = ''
default['nservicebus']['servicepulse']['url'] = ''
default['nservicebus']['servicecontrol']['sha256checksum'] = ''
default['nservicebus']['servicecontrol']['url'] = ''
default['nservicebus']['license']['url'] = ''
